# Generated by Django 4.2.1 on 2023-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
