# Generated by Django 4.2.1 on 2023-06-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_admin',
        ),
    ]
