# Generated by Django 4.2.1 on 2023-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_failed_login',
            field=models.DateTimeField(null=True),
        ),
    ]
