# Generated by Django 4.2.1 on 2023-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_route_end_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
