# Generated by Django 4.2.1 on 2023-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
