# Generated by Django 4.2.1 on 2023-11-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recoverycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
