# Generated by Django 4.2.1 on 2023-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_searchedlocation'),
        ('api', '0008_rename_user_id_appuser_id'),
    ]

    operations = [
    ]
