# Generated by Django 4.2.1 on 2023-12-14 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20231121_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite route',
                'verbose_name_plural': 'Favourite routes',
            },
        ),
    ]
