# Generated by Django 4.2.1 on 2023-12-18 08:05

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_favroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=api.models.EncryptedEmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=api.models.EncryptedCharField(max_length=50, unique=True),
        ),
    ]
