# Generated by Django 4.2.1 on 2023-12-18 08:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_appuser_email_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_hash',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='username_hash',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=api.models.EncryptedEmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=api.models.EncryptedCharField(max_length=250, unique=True),
        ),
    ]
